site_name: twai-pipeline
site_dir: public/docs
repo_url: https://github.com/aai-institute/twai-pipeline
edit_uri: edit/main/docs/
site_url: https://aai-institute.github.io/twai-pipeline/

# To validate all internal links exist. Does not work in ipynb files
strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - Reader's Guide: readers-guide.md
  - Showcase:
      - showcase/index.md
      - showcase/risk-classification.md
      - showcase/system-overview.md
  - Engineering Practice:
      - engineering-practice/reference-architecture.md
      - engineering-practice/containerization.md
      - engineering-practice/experiment-tracking.md
      - engineering-practice/explainability.md
      - engineering-practice/model-registry.md
      - engineering-practice/model-monitoring.md
      - engineering-practice/model-serving.md
      - engineering-practice/inference-log.md
      - engineering-practice/operational-monitoring.md
      - engineering-practice/accuracy.md
      - engineering-practice/orchestration.md
      - Data Governance:
          - engineering-practice/data-governance/index.md
          - engineering-practice/data-governance/data-quality.md
          - engineering-practice/data-governance/data-versioning.md
          - engineering-practice/data-governance/bias-mitigation.md
  - AI Act Conformity:
      - conformity/index.md
      - Documents:
          - conformity/documents/index.md
          - conformity/documents/technical-documentation.md
          - conformity/documents/instructions-for-use.md
  - Tags:
      - tags.md
  - acknowledgments.md

plugins:
  - callouts
  - section-index
  - mkdocs-backlinks:
      ignored_pages:
        ["Engineering Practice", "Data Governance", "Reader's Guide", "Home"]
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            line_length: 100
            show_bases: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            merge_init_into_class: false
            filters: ["!^_{1,2}"]
  - mike:
      canonical_version: latest
  - meta
  - privacy
  - search:
  - tags
  - include_dir_to_nav:
      file_pattern: '.*\.(md|ipynb)$'

markdown_extensions:
  # Render textual references to AI Act as links
  - markdown_ex
  # python-markdown extensions: https://python-markdown.github.io/extensions/
  - admonition
  - attr_list
  - md_in_html
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  # pymdown-extensions: https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: "material"
  custom_dir: docs/_theme_overrides
  logo: _images/logos/baiaa-icon.svg
  favicon: _images/logos/baiaa-icon.svg
  font:
    text: Source Sans Pro # Arial replacement
    code: Source Code Pro
  icon:
    logo: _images/logos/baiaa-icon.svg
    repo: fontawesome/brands/github
    admonition:
      success: octicons/law-24
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: aai-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  copyright_link: https://appliedai-institute.de
  generator: false
  pre_release: !ENV [DOCS_PRERELEASE, false]
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aai-institute/twai-pipeline
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/appliedai-institute-for-europe-ggmbh/
    - icon: fontawesome/solid/section
      link: https://appliedai-institute.de/impressum
      name: Impressum / Imprint

extra_css:
  - _styles/extra.css
  - _styles/theme.css
