site_name: twai-pipeline
site_dir: public/docs
repo_url: https://github.com/aai-institute/twai-pipeline
edit_uri: edit/main/docs/

# To validate all internal links exist. Does not work in ipynb files
strict: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

copyright: Copyright &copy; 2025 <a href="https://appliedai-institute.de" target="_blank" rel="noopener">appliedAI Institute for Europe gGmbH</a><br>The appliedAI Institute for Europe gGmbH is supported by the KI-Stiftung Heilbronn gGmbH.

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - getting-started/first-steps.md
      - getting-started/ai-act-in-a-nutshell.md
  - How-to:
      - how-to/index.md
  - Explanations:
      - explanations/index.md
      - explanations/uncertainty-quantification.md
      - explanations/explainability.md
      - explanations/bias.md
      - explanations/fairness.md
      - explanations/data-governance.md
      - explanations/accuracy.md
      - explanations/cybersecurity.md
      - explanations/interoperability.md
      - explanations/privacy-and-data-security.md
      - explanations/record-keeping.md
      - explanations/robustness.md
      - explanations/technical-documentation.md
      - explanations/traceability.md
      - explanations/transparency.md

plugins:
  - callouts
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            line_length: 100
            show_bases: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            merge_init_into_class: false
            filters: ["!^_{1,2}"]
  - mike:
      canonical_version: latest
  - privacy
  - search:
  - git-revision-date-localized:
      type: iso_date
      strict: false
      fallback_to_build_date: true

markdown_extensions:
  # Render textual references to AI Act as links
  - markdown_ex
  # python-markdown extensions: https://python-markdown.github.io/extensions/
  - admonition
  - attr_list
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  # pymdown-extensions: https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: "material"
  custom_dir: docs/_theme_overrides
  logo: _images/aai-logo-cropped.png
  favicon: _images/aai-favicon.png
  font:
    text: IBM Plex Sans # Arial replacement
    code: Source Code Pro
  icon:
    logo: _images/aai-favicon.png
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for light mode
    - scheme: aai-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  copyright_link: https://appliedai-institute.de
  generator: false
  pre_release: !ENV [DOCS_PRERELEASE, false]
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aai-institute/twai-pipeline
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/appliedai-institute-for-europe-ggmbh/
    - icon: fontawesome/solid/section
      link: https://appliedai-institute.de/impressum
      name: Impressum / Imprint

extra_css:
  - _styles/extra.css
  - _styles/theme.css
