[project]
name = "twai-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightgbm>=4.5.0",
    "mlflow>=2.19.0",
    "more-itertools>=10.5.0",
    "notebook>=7.3.2",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "sensai>=1.3.0",
    "ucimlrepo>=0.0.7",
    "xgboost>=2.1.3",
]

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocstrings-python>=1.13.0",
]
dev = []
