[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "hr-assistant"
version = "0.1.0"
description = "An ML assistant for HR professionals."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.1.3",
    "evidently>=0.6.1",
    "lightgbm>=4.5.0",
    "mlflow>=2.19.0",
    "more-itertools>=10.5.0",
    "notebook>=7.3.2",
    "numpy>2",
    "pandas>=2.2.3",
    "sensai>=1.3.0",
    "ucimlrepo>=0.0.7",
    "xgboost>=2.1.3",
]

[dependency-groups]
docs = [
    "mkdocs",
    "mkdocs-callouts",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-git-revision-date-localized-plugin",
    "mkdocs-include-dir-to-nav",
    "mike",
]
deploy = ["fastapi[standard]>=0.115.7"]
dev = ["pytest>=8.3.4", "ruff>=0.9.3"]

[tool.ruff]
preview = true
exclude = ["openapi_client"]
line-length = 88

# FIXME: Exclude existing non-compliant code for now
extend-exclude = ["scripts/**", "src/adult/**"]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "W",
    "B",
    "UP",
    "C4",
    "PYI",
    "FAST",
    "T10",  # prevent stray debug breakpoints
]
ignore = [
    "E501",    # Line too long
    "RUF029",  # Unused Async (FastAPI routes are async)
    "FAST003", # FastAPI unused path parameter (they can be consumed by dependencies)
]
