@base_url = http://localhost:8000

### Model info

GET {{base_url}}/model/info

### Inference request for a single record

POST {{base_url}}/model/predict
Content-Type: application/json

{
  "age": 21,
  "workclass": "Private",
  "education": "HS-grad",
  "education-num": 9,
  "marital-status": "Never-married",
  "occupation": "Adm-clerical",
  "relationship": "Own-child",
  "race": "White",
  "sex": "Female",
  "capital-gain": 0,
  "capital-loss": 0,
  "hours-per-week": 45,
  "native-country": "United-States"
}

### Batch inference request

POST {{base_url}}/model/predict
Content-Type: application/json

[
  {
    "age": 21,
    "workclass": "Private",
    "education": "HS-grad",
    "education-num": 9,
    "marital-status": "Never-married",
    "occupation": "Adm-clerical",
    "relationship": "Own-child",
    "race": "White",
    "sex": "Female",
    "capital-gain": 0,
    "capital-loss": 0,
    "hours-per-week": 45,
    "native-country": "United-States"
  },
  {
    "age": 45,
    "workclass": "Private",
    "education": "HS-grad",
    "education-num": 9,
    "marital-status": "Married-civ-spouse",
    "occupation": "Exec-managerial",
    "relationship": "Own-child",
    "race": "White",
    "sex": "Male",
    "capital-gain": 0,
    "capital-loss": 0,
    "hours-per-week": 90,
    "native-country": "United-States"
  }
]


### Flush logs
POST {{base_url}}/model/flush-logs