@base_url = http://localhost:8000

### Model info

GET {{base_url}}/model/info

### Inference request for a single record

POST {{base_url}}/model/predict
Content-Type: application/json

{
  "A_SEX": 1,
  "A_ENRLW": 0,
  "A_FTPT": 0,
  "A_HSCOL": 0,
  "A_MARITL": 1,
  "P_STAT": 1,
  "PECERT1": 2,
  "PEHSPNON": 2,
  "PRDTHSP": 0,
  "PRDASIAN": -1,
  "PRDTRACE": 1,
  "PENATVTY": 57,
  "PRCITSHP": 1,
  "PRDISFLG": 2,
  "A_LFSR": 1,
  "A_CLSWKR": 6,
  "A_FTLF": 1,
  "A_UNMEM": 0,
  "A_UNTYPE": 0,
  "PRUNTYPE": 0,
  "A_WKSTAT": 2,
  "INDUSTRY": 7071,
  "CLWK": 3,
  "A_MJIND": 9,
  "A_MJOCC": 1,
  "PEMLR": 1,
  "ERN_SRCE": 2,
  "COV": 1,
  "HEA": 4,
  "A_AGE": 70,
  "A_WKSLK": 0,
  "WKSWORK": 15,
  "A_USLHRS": 40,
  "HRSWK": 1,
  "A_HRS1": 40,
  "NOEMP": 1,
  "A_GRSWK": 0,
  "A_HRSPAY": -1,
  "ERN_VAL": -4500,
  "WAGEOTR": 0,
  "AGI": 0,
  "A_FNLWGT": 151541,
  "A_HGA": 43
}

### Batch inference request

POST {{base_url}}/model/predict
Content-Type: application/json

[
  {
    "A_SEX": 1,
    "A_ENRLW": 0,
    "A_FTPT": 0,
    "A_HSCOL": 0,
    "A_MARITL": 1,
    "P_STAT": 1,
    "PECERT1": 2,
    "PEHSPNON": 2,
    "PRDTHSP": 0,
    "PRDASIAN": -1,
    "PRDTRACE": 1,
    "PENATVTY": 57,
    "PRCITSHP": 1,
    "PRDISFLG": 2,
    "A_LFSR": 1,
    "A_CLSWKR": 6,
    "A_FTLF": 1,
    "A_UNMEM": 0,
    "A_UNTYPE": 0,
    "PRUNTYPE": 0,
    "A_WKSTAT": 2,
    "INDUSTRY": 7071,
    "CLWK": 3,
    "A_MJIND": 9,
    "A_MJOCC": 1,
    "PEMLR": 1,
    "ERN_SRCE": 2,
    "COV": 1,
    "HEA": 4,
    "A_AGE": 70,
    "A_WKSLK": 0,
    "WKSWORK": 15,
    "A_USLHRS": 40,
    "HRSWK": 1,
    "A_HRS1": 40,
    "NOEMP": 1,
    "A_GRSWK": 0,
    "A_HRSPAY": -1,
    "ERN_VAL": -4500,
    "WAGEOTR": 0,
    "AGI": 0,
    "A_FNLWGT": 151541,
    "A_HGA": 43
  },
  {
    "A_SEX": 1,
    "A_ENRLW": 0,
    "A_FTPT": 0,
    "A_HSCOL": 0,
    "A_MARITL": 1,
    "P_STAT": 1,
    "PECERT1": 2,
    "PEHSPNON": 2,
    "PRDTHSP": 0,
    "PRDASIAN": -1,
    "PRDTRACE": 1,
    "PENATVTY": 57,
    "PRCITSHP": 1,
    "PRDISFLG": 2,
    "A_LFSR": 1,
    "A_CLSWKR": 6,
    "A_FTLF": 1,
    "A_UNMEM": 0,
    "A_UNTYPE": 0,
    "PRUNTYPE": 0,
    "A_WKSTAT": 2,
    "INDUSTRY": 7071,
    "CLWK": 3,
    "A_MJIND": 9,
    "A_MJOCC": 1,
    "PEMLR": 1,
    "ERN_SRCE": 2,
    "COV": 1,
    "HEA": 4,
    "A_AGE": 70,
    "A_WKSLK": 0,
    "WKSWORK": 15,
    "A_USLHRS": 40,
    "HRSWK": 1,
    "A_HRS1": 40,
    "NOEMP": 1,
    "A_GRSWK": 0,
    "A_HRSPAY": -1,
    "ERN_VAL": -4500,
    "WAGEOTR": 0,
    "AGI": 0,
    "A_FNLWGT": 151541,
    "A_HGA": 43
  }
]