{
 "title": "MLflow",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": true,
 "panels": [
  {
   "title": "Server version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mlflow_exporter_info" }
   ]
  },
  {
   "title": "HTTP request success rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mlflow_http_request_total{status=\"200\"}[$__rate_interval])) / (sum(increase(mlflow_http_request_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(le) (rate(mlflow_http_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}