{
 "title": "ML Model",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": true,
 "panels": [
  {
   "title": "Number of inference requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_infer_request_success_total + model_infer_request_failure_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(model_infer_request_duration_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference request success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(model_infer_request_failure_total / (model_infer_request_success_total + model_infer_request_failure_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request latencies",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (rate(rest_server_request_duration_seconds_bucket{job='ml-model'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}